/**
 * The canaries: things that must stay true about TRF5, checked where they are cheapest to check.
 *
 * The design principle is one sentence: **a scraper must never return zero results quietly.**
 * Every one of these guards a change the site could make that would leave the crawler running
 * happily and producing nothing — or worse, producing a little and declaring it complete. When
 * one trips the run stops with exit code 3 and a message naming what changed, because that is a
 * human's problem, not something to retry six times.
 *
 * Each id is referenced from the parser that raises it and from `docs/GUIDE.md`.
 */
import type { SanityCheck } from '../../core/ports/siteAdapter.js';

export const TRF5_CANARIES: readonly SanityCheck[] = [
  {
    id: 'C-1',
    severity: 'error',
    description:
      'The search action id is still discoverable. The real search is fired by an autogenerated ' +
      'JSF id (`fPP:j_id244` today), not by the visible button; JSF renumbers it on redeploy, so ' +
      'it is derived by regex on every run and never hardcoded.',
  },
  {
    id: 'C-2',
    severity: 'error',
    description:
      'The reCAPTCHA hook is still inert. The page loads reCAPTCHA but the submit hook reads ' +
      '`if (false)`. If that flips, or a `g-recaptcha-response` field appears in the form, every ' +
      'search would silently return nothing.',
  },
  {
    id: 'C-3',
    severity: 'error',
    description:
      'Every field the search form needs is present. A missing date field or ViewState means the ' +
      'form was redesigned and the request we would send no longer matches it.',
  },
  {
    id: 'C-4',
    severity: 'error',
    description:
      'The row cap the site reports still matches what the partition tree was built against. A ' +
      'different cap invalidates every leaf already resolved, so it is fatal rather than adaptive.',
  },
  {
    id: 'C-5',
    severity: 'error',
    description:
      'The golden probe still returns what the reconnaissance measured (24 rows for 2024-05-15, ' +
      'untruncated). Also catches the button trap: a response that never re-rendered the results ' +
      'grid is not an empty day.',
  },
  {
    id: 'C-6',
    severity: 'error',
    description:
      'No extracted string carries a mojibake signature. Ten occurrences in one run is fatal: it ' +
      'means the charset detection is wrong for this deployment, not that one field is odd.',
  },
  {
    id: 'C-7',
    severity: 'error',
    description:
      'The detail page still carries its expected labels and sections. Three consecutive ' +
      'failures mean the page changed, not that three cases are unusual.',
  },
  {
    id: 'C-8',
    severity: 'warn',
    description:
      'The edge probes outside the root range come back empty. If they do not, data exists ' +
      'outside the window being crawled and the root must be widened.',
  },
  {
    id: 'C-9',
    severity: 'warn',
    description:
      'No case appears in two disjoint primary leaves. If one does, `dataAutuação` is not the ' +
      'single day the partitioning assumes and the completeness argument needs revisiting.',
  },
  {
    id: 'C-10',
    severity: 'error',
    description:
      'The response is not the load balancer\'s "Requisição - Rejeitada" page. Measured: the F5 ' +
      'returns it with status 200, so it must be detected by content or it reads as a site change.',
  },
];

export function canaryById(id: string): SanityCheck | undefined {
  return TRF5_CANARIES.find((c) => c.id === id);
}
