/**
 * Builds the A4J search POST.
 *
 * Two things here are measurements, not conventions, and both were expensive to learn:
 *
 * **The body is encoded in ISO-8859-1**, the charset of the page that served the form — which is
 * *not* the charset of the response the form produces (that one is UTF-8). Encoding it as UTF-8
 * makes the server read `APELAÇÃO CÍVEL` as mojibake and match nothing: zero rows, no error, no
 * banner, indistinguishable from a day with no such cases. That single mistake made the entire
 * secondary partition axis look impossible. See `docs/spike-fase0.md` §5.
 *
 * **The search is fired by `searchActionId`**, the autogenerated JSF id, never by the visible
 * button. Posting the button re-renders an empty panel and returns ~2.8 KB.
 *
 * Every field the form declares is sent, including the empty ones. JSF binds the whole view, and
 * an omitted field is not "unset" to it — it is a view that no longer matches the one it rendered.
 */
import type { DateRange } from '../../core/domain/types.js';
import { isoToBrDate, isoToBrMonth } from '../../core/domain/dates.js';
import { urlencodeForm, type EncodedForm } from '../../shared/form.js';
import type { FormMeta } from './parsers/listView.js';

export interface SearchFormInput {
  meta: FormMeta;
  range: DateRange;
  /** Secondary-axis constraints. Only `classe` is supported today. */
  facets?: Record<string, string>;
  /**
   * The `MM/yyyy` the RichFaces calendar widget carries alongside each date. The server does not
   * filter on it, but it is part of the view state the component expects.
   */
  currentMonth?: string;
}

export function buildSearchFields(input: SearchFormInput): Record<string, string> {
  const { meta, range, facets = {} } = input;
  const currentMonth = input.currentMonth ?? isoToBrMonth(range.ini);

  return {
    AJAXREQUEST: '_viewRoot',
    fPP: 'fPP',
    'fPP:numProcesso-inputNumeroProcessoDecoration:numProcesso-inputNumeroProcesso':
      facets['numProcesso'] ?? '',
    mascaraProcessoReferenciaRadio: 'on',
    'fPP:j_id162:processoReferenciaInput': '',
    'fPP:dnp:nomeParte': '',
    'fPP:j_id180:nomeAdv': '',
    'fPP:j_id189:classeJudicial': facets['classe'] ?? '',
    tipoMascaraDocumento: 'on',
    'fPP:dpDec:documentoParte': '',
    'fPP:Decoration:numeroOAB': '',
    'fPP:Decoration:estadoComboOAB': 'org.jboss.seam.ui.NoSelectionConverter.noSelectionValue',
    'fPP:Decoration:j_id223': '',
    'fPP:dataAutuacaoDecoration:dataAutuacaoInicioInputDate': isoToBrDate(range.ini),
    'fPP:dataAutuacaoDecoration:dataAutuacaoInicioInputCurrentDate': currentMonth,
    'fPP:dataAutuacaoDecoration:dataAutuacaoFimInputDate': isoToBrDate(range.fim),
    'fPP:dataAutuacaoDecoration:dataAutuacaoFimInputCurrentDate': currentMonth,
    autoScroll: '',
    'javax.faces.ViewState': meta.viewState,
    // The line that actually runs a search.
    [meta.searchActionId]: meta.searchActionId,
    'AJAX:EVENTS_COUNT': '1',
  };
}

/** The encoded body, ready to send. The charset is the form's, not the response's. */
export function buildSearchBody(input: SearchFormInput): EncodedForm {
  return urlencodeForm(buildSearchFields(input), 'iso-8859-1');
}

export const SEARCH_HEADERS: Readonly<Record<string, string>> = {
  'X-Requested-With': 'XMLHttpRequest',
};
