/**
 * Parses the search page into everything needed to post a search.
 *
 * The one thing worth reading closely is `searchActionId`. The visible button (`fPP:searchProcessos`)
 * **does not run a search**: posting with it re-renders an empty message panel and returns about
 * 2.8 KB. The real action is the JSF id embedded in the `executarPesquisa` script — `fPP:j_id244`
 * today — and JSF renumbers those on every redeploy. Hardcoding it would work until the court
 * next deploys, at which point the crawler would return zero rows and look like it was working.
 * So it is derived here, on every run, and its absence is fatal (canary C-1).
 */
import { load } from 'cheerio';
import { SiteChangedError } from '../../../core/ports/siteAdapter.js';
import { cleanText } from '../../../core/domain/text.js';

export interface FormMeta {
  /** Absolute path to POST to, including the `;jsessionid=…` the server appends. */
  action: string;
  /** The autogenerated JSF id that actually runs the search. Never hardcoded. */
  searchActionId: string;
  viewState: string;
  /** True if the reCAPTCHA hook is live. Any value but `false` stops the run. */
  captchaEnabled: boolean;
  /** Names of the form's input fields, used to check nothing expected disappeared. */
  fieldNames: string[];
}

/** The load balancer answers a rejected request with status 200 and this page (canary C-10). */
export const WAF_REJECTION_PATTERN = /Requisi[^<]{0,20}Rejeitada/i;

/**
 * The fields the search body must carry. Derived from the reconnaissance and re-checked here so
 * a redesigned form fails at bootstrap rather than by returning nothing.
 */
export const REQUIRED_FIELDS: readonly string[] = [
  'fPP:numProcesso-inputNumeroProcessoDecoration:numProcesso-inputNumeroProcesso',
  'fPP:dnp:nomeParte',
  'fPP:dpDec:documentoParte',
  'fPP:Decoration:numeroOAB',
  'fPP:Decoration:estadoComboOAB',
  'fPP:dataAutuacaoDecoration:dataAutuacaoInicioInputDate',
  'fPP:dataAutuacaoDecoration:dataAutuacaoFimInputDate',
  'javax.faces.ViewState',
];

const FORM_ACTION = /<form id="fPP"[^>]*action="([^"]+)"/;
const SEARCH_ACTION_ID =
  /executarPesquisa\s*=\s*function\s*\(\)\s*\{[\s\S]{0,400}?'parameters'\s*:\s*\{\s*'(fPP:j_id\d+)'/;
const VIEW_STATE = /name="javax\.faces\.ViewState"[^>]*value="([^"]*)"/;
/** The inert hook: `function executarReCaptcha(){ if (false) { … } }`. */
const CAPTCHA_DISABLED = /function\s+executarReCaptcha\s*\(\s*\)\s*\{\s*if\s*\(\s*false\s*\)/;

export function parseListView(html: string): FormMeta {
  if (WAF_REJECTION_PATTERN.test(html)) {
    throw new SiteChangedError(
      'C-10',
      'the load balancer returned its "Requisição - Rejeitada" page with status 200. ' +
        'This is a WAF block, not a site change: lower the concurrency and retry.',
      { bytes: html.length },
    );
  }

  const action = FORM_ACTION.exec(html)?.[1];
  if (action === undefined) {
    throw new SiteChangedError('C-3', 'the search form (id="fPP") is no longer in the page', {
      bytes: html.length,
      title: titleOf(html),
    });
  }

  const searchActionId = SEARCH_ACTION_ID.exec(html)?.[1];
  if (searchActionId === undefined) {
    throw new SiteChangedError(
      'C-1',
      'the executarPesquisa script no longer yields a search action id. The visible button does ' +
        'not run a search, so without this id every query would return an empty panel.',
      { bytes: html.length },
    );
  }

  const viewState = VIEW_STATE.exec(html)?.[1];
  if (viewState === undefined) {
    throw new SiteChangedError('C-3', 'javax.faces.ViewState is missing from the form', {
      bytes: html.length,
    });
  }

  const captchaEnabled = !CAPTCHA_DISABLED.test(html);
  if (captchaEnabled) {
    throw new SiteChangedError(
      'C-2',
      'the reCAPTCHA hook is no longer `if (false)`. Searches would silently return nothing; ' +
        'this environment may have had its captcha enabled.',
      {},
    );
  }

  const fieldNames = collectFieldNames(html);
  if (/name="g-recaptcha-response"/.test(html)) {
    throw new SiteChangedError('C-2', 'a g-recaptcha-response field appeared in the form', {});
  }

  const missing = REQUIRED_FIELDS.filter((name) => !fieldNames.includes(name));
  if (missing.length > 0) {
    throw new SiteChangedError(
      'C-3',
      `the search form no longer carries ${String(missing.length)} expected field(s): ${missing.join(', ')}`,
      { missing, found: fieldNames.length },
    );
  }

  return { action, searchActionId, viewState, captchaEnabled, fieldNames };
}

function collectFieldNames(html: string): string[] {
  const $ = load(html);
  const names = new Set<string>();
  $('#fPP')
    .find('input, select, textarea')
    .each((_, el) => {
      const name = $(el).attr('name');
      if (name !== undefined && name !== '') names.add(name);
    });
  // ViewState lives in its own hidden field that some renderings place outside the form element.
  if (VIEW_STATE.test(html)) names.add('javax.faces.ViewState');
  return [...names];
}

function titleOf(html: string): string {
  return cleanText(/<title>([^<]{0,80})/.exec(html)?.[1] ?? '');
}
