/**
 * Every canary is tested twice: once that it passes on the real page, and once that it *fails*
 * on a page mutated the way the site could plausibly change. A canary that has never been red is
 * not a canary, it is decoration.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parseListView } from '../../src/sites/br-trf5/parsers/listView.js';
import { SiteChangedError } from '../../src/core/ports/siteAdapter.js';
import { TRF5_CANARIES, canaryById } from '../../src/sites/br-trf5/canaries.js';
import { decodeLatin1 } from '../../src/shared/latin1.js';

const FIXTURES = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  'src',
  'sites',
  'br-trf5',
  'fixtures',
);

const listView = readFileSync(join(FIXTURES, '01-listview-form.html'), 'utf8');

/** Asserts the parser raises the given canary, and returns the error for further checks. */
function expectCanary(html: string, id: string): SiteChangedError {
  try {
    parseListView(html);
  } catch (error) {
    expect(error).toBeInstanceOf(SiteChangedError);
    const site = error as SiteChangedError;
    expect(site.canaryId).toBe(id);
    return site;
  }
  throw new Error(`expected canary ${id} to trip, but parsing succeeded`);
}

describe('parseListView on the real page', () => {
  it('extracts the form action, including the jsessionid the server appends', () => {
    const meta = parseListView(listView);
    expect(meta.action).toContain('/pjeconsulta/ConsultaPublica/listView.seam');
    expect(meta.action).toContain(';jsessionid=');
  });

  it('derives the search action id from the executarPesquisa script', () => {
    // The value happens to be fPP:j_id244 today. The test asserts the *shape*, because the
    // number is autogenerated and pinning it would recreate the bug this guards against.
    const meta = parseListView(listView);
    expect(meta.searchActionId).toMatch(/^fPP:j_id\d+$/);
  });

  it('does not pick up the visible button, which does not run a search', () => {
    const meta = parseListView(listView);
    expect(meta.searchActionId).not.toBe('fPP:searchProcessos');
    expect(listView).toContain('fPP:searchProcessos');
  });

  it('extracts the ViewState', () => {
    expect(parseListView(listView).viewState).toBe('j_id1');
  });

  it('sees the captcha hook as inert', () => {
    expect(parseListView(listView).captchaEnabled).toBe(false);
  });

  it('finds every field the search body needs', () => {
    const meta = parseListView(listView);
    expect(meta.fieldNames).toContain('fPP:dataAutuacaoDecoration:dataAutuacaoInicioInputDate');
    expect(meta.fieldNames).toContain('fPP:j_id189:classeJudicial');
    expect(meta.fieldNames.length).toBeGreaterThan(10);
  });
});

describe('canaries trip on a changed site', () => {
  it('C-1: the search action id can no longer be derived', () => {
    // A JSF redeploy that renames the function, or a page that stops emitting the script.
    const mutated = listView.replace(
      /executarPesquisa\s*=\s*function/g,
      'executarOutraCosa=function',
    );
    const error = expectCanary(mutated, 'C-1');
    expect(error.message).toContain('visible button');
  });

  it('C-1 tolerates the id itself being renumbered, which is normal', () => {
    const renumbered = listView.replace(/fPP:j_id244/g, 'fPP:j_id999');
    expect(parseListView(renumbered).searchActionId).toBe('fPP:j_id999');
  });

  it('C-2: the captcha hook flipped to if (true)', () => {
    const mutated = listView.replace(
      /function\s+executarReCaptcha\s*\(\s*\)\s*\{\s*if\s*\(\s*false\s*\)/,
      'function executarReCaptcha(){ if (true)',
    );
    const error = expectCanary(mutated, 'C-2');
    expect(error.message).toContain('silently return nothing');
  });

  it('C-2: a g-recaptcha-response field appeared', () => {
    const mutated = listView.replace(
      '<form id="fPP"',
      '<input name="g-recaptcha-response" type="hidden"/><form id="fPP"',
    );
    expectCanary(mutated, 'C-2');
  });

  it('C-3: the ViewState disappeared', () => {
    const mutated = listView.replace(/name="javax\.faces\.ViewState"/g, 'name="something-else"');
    expectCanary(mutated, 'C-3');
  });

  it('C-3: a date field was renamed', () => {
    const mutated = listView.replace(
      /fPP:dataAutuacaoDecoration:dataAutuacaoInicioInputDate/g,
      'fPP:dataAutuacaoDecoration:dataInicioNova',
    );
    const error = expectCanary(mutated, 'C-3');
    expect(error.message).toContain('dataAutuacaoInicioInputDate');
  });

  it('C-3: the form itself is gone', () => {
    const mutated = listView.replace('<form id="fPP"', '<form id="somethingElse"');
    expectCanary(mutated, 'C-3');
  });

  it('C-10: the load balancer returned its rejection page with status 200', () => {
    // Reproduced byte for byte from the live measurement: latin1 bytes, status 200, no form.
    const waf = decodeLatin1(
      new Uint8Array(Buffer.from('<html><title>Requisição - Rejeitada</title></html>', 'latin1')),
    );
    const error = expectCanary(waf, 'C-10');
    expect(error.message).toContain('WAF block');
    expect(error.message).toContain('not a site change');
  });
});

describe('the canary catalogue', () => {
  it('has a unique id and a description for each entry', () => {
    const ids = TRF5_CANARIES.map((c) => c.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const canary of TRF5_CANARIES) {
      expect(canary.description.length).toBeGreaterThan(40);
      expect(['error', 'warn']).toContain(canary.severity);
    }
  });

  it('documents every canary this parser can raise', () => {
    for (const id of ['C-1', 'C-2', 'C-3', 'C-10']) {
      expect(canaryById(id), `canary ${id} is raised but not documented`).toBeDefined();
    }
  });
});
