/**
 * A fake PJe, faithful enough to be the system's second site.
 *
 * Two jobs, and the second is the one that matters most:
 *
 * **1. It makes the untestable testable.** Provoking a 429 against a real tribunal would be
 * abusive, and the reconnaissance could not reproduce one within a responsible request budget.
 * Rate limiting is nevertheless an explicit evaluation criterion, so it is implemented in full
 * and proved here — with and without `Retry-After`, alongside 5xx, dropped connections, expired
 * sessions, HTML where a PDF was promised, and truncated PDFs.
 *
 * **2. It keeps the abstraction honest.** This server is registered as a real `SiteAdapter`, so
 * the multi-site claim is exercised by a second implementation rather than asserted by an
 * interface with one. An abstraction with a single implementation is a guess.
 *
 * It reproduces the parts of the real contract the crawler actually depends on: cookies with
 * path scoping, a search action id that is **regenerated on every boot** (so a hardcoded one
 * fails immediately), the row cap with its banner, the empty-result footer with no number, the
 * redirect to a document store, and — measured on the live site — the rejection page the load
 * balancer returns with status 200 for a request carrying an empty `Cookie` header.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import type { AddressInfo } from 'node:net';
import { buildDataset, type Dataset, type SyntheticCase } from './dataset.js';

export interface FaultInjection {
  /** Answer the next `times` requests with this status. */
  status?: number;
  /** Seconds to advertise in `Retry-After`. Omitted to test the no-header path. */
  retryAfter?: number;
  /** An HTTP-date instead of seconds, which the spec also allows and clients often mishandle. */
  retryAfterDate?: boolean;
  times?: number;
  /** Delay the response, to exercise timeouts. */
  delayMs?: number;
  /** Destroy the socket without answering. */
  dropConnection?: boolean;
  /** Invalidate every issued `ca`, so the next detail request behaves like a dead session. */
  expireSession?: boolean;
  /** Return an HTML page where a PDF was promised — the real symptom of a lost session. */
  htmlInsteadOfPdf?: boolean;
  /** Cut the PDF short, to exercise the truncation check. */
  truncatePdfAt?: number;
  /** Report a different cap, which must be fatal rather than adaptive. */
  cap?: number;
  /** Turn the captcha hook on, which must stop the run. */
  captcha?: boolean;
  /** Rename the search action id mid-run, as a redeploy would. */
  renameActionId?: boolean;
  /** Serve responses as latin1 instead of UTF-8. */
  latin1?: boolean;
  /** Answer with the load balancer's rejection page, at status 200. */
  wafRejection?: boolean;
}

export interface FakePjeOptions {
  seed?: number;
  days?: number;
  start?: string;
  cap?: number;
  /** Emit the truncation banner. Turned off to prove a full page still forces a split. */
  emitBanner?: boolean;
  /** Fixed port. Zero — the default — lets the OS pick one, which is what tests want. */
  port?: number;
  /** Interface to bind. Loopback by default; a container has to bind all of them. */
  host?: string;
}

export interface FakePjeServer {
  url: string;
  /** The port actually bound, which matters when the requested one was zero. */
  port: number;
  dataset: Dataset;
  /** How many requests have been served, by path kind. */
  counts: Record<string, number>;
  /** Queue a fault for the next matching requests. */
  inject: (fault: FaultInjection) => void;
  clearFaults: () => void;
  /** The action id the current boot expects. Regenerated on `renameActionId`. */
  searchActionId: () => string;
  close: () => Promise<void>;
}

const APP = '/pjeconsulta';

export async function startFakePje(options: FakePjeOptions = {}): Promise<FakePjeServer> {
  const dataset = buildDataset({
    seed: options.seed ?? 20260827,
    days: options.days ?? 90,
    start: options.start ?? '2024-01-01',
    cap: options.cap ?? 30,
  });
  const emitBanner = options.emitBanner ?? true;

  // Autogenerated per boot, exactly as JSF does. A crawler that hardcodes it fails on the first
  // search rather than silently returning nothing.
  let actionId = `fPP:j_id${String(200 + Math.floor(dataset.cases.length % 90))}`;
  let sessionEpoch = 1;
  let pending: FaultInjection | null = null;
  let pendingLeft = 0;
  const counts: Record<string, number> = { list: 0, search: 0, detail: 0, pdf: 0, docstore: 0 };

  const takeFault = (): FaultInjection | null => {
    if (pending === null || pendingLeft <= 0) return null;
    pendingLeft--;
    const fault = pending;
    if (pendingLeft === 0) pending = null;
    return fault;
  };

  const server: Server = createServer((req, res) => {
    void handle(req, res);
  });

  async function handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    const url = new URL(req.url ?? '/', 'http://localhost');
    const body = await readBody(req);
    const fault = takeFault();

    if (fault?.dropConnection === true) {
      req.socket.destroy();
      return;
    }
    if (fault?.delayMs !== undefined) {
      await new Promise((resolve) => setTimeout(resolve, fault.delayMs));
    }
    if (fault?.expireSession === true) sessionEpoch++;
    if (fault?.renameActionId === true) actionId = `fPP:j_id${String(900 + sessionEpoch)}`;
    if (fault?.status !== undefined) {
      const headers: Record<string, string> = { 'content-type': 'text/html;charset=UTF-8' };
      if (fault.retryAfter !== undefined) {
        headers['retry-after'] =
          fault.retryAfterDate === true
            ? new Date(Date.now() + fault.retryAfter * 1000).toUTCString()
            : String(fault.retryAfter);
      }
      res.writeHead(fault.status, headers);
      res.end(`<html><body>injected ${String(fault.status)}</body></html>`);
      return;
    }
    if (fault?.wafRejection === true) {
      // Status 200 with an error page: measured behaviour of the real load balancer.
      res.writeHead(200, { 'content-type': 'text/html;charset=ISO-8859-1' });
      res.end(Buffer.from('<html><title>Requisição - Rejeitada</title></html>', 'latin1'));
      return;
    }

    // The same measured trap: an *empty* Cookie header is rejected, a missing one is fine.
    if (req.headers.cookie === '') {
      res.writeHead(200, { 'content-type': 'text/html;charset=ISO-8859-1' });
      res.end(Buffer.from('<html><title>Requisição - Rejeitada</title></html>', 'latin1'));
      return;
    }

    const charset = fault?.latin1 === true ? 'latin1' : 'utf8';

    if (url.pathname === `${APP}/ConsultaPublica/listView.seam` && req.method === 'GET') {
      counts['list'] = (counts['list'] ?? 0) + 1;
      res.writeHead(200, {
        'content-type': 'text/html;charset=ISO-8859-1',
        'set-cookie': [
          `JSESSIONID=fake-${String(sessionEpoch)}.node-1; Path=${APP}`,
          'ROUTER_ID=fake; Path=/',
        ],
      });
      res.end(Buffer.from(listViewHtml(actionId, fault?.captcha === true), charset));
      return;
    }

    if (url.pathname === `${APP}/ConsultaPublica/listView.seam` && req.method === 'POST') {
      counts['search'] = (counts['search'] ?? 0) + 1;
      const fields = parseForm(body);
      // The button trap: without the current action id, no search runs.
      if (fields[actionId] === undefined) {
        res.writeHead(200, { 'content-type': 'text/xml;charset=UTF-8' });
        res.end(buttonTrapHtml());
        return;
      }
      const cap = fault?.cap ?? dataset.cap;
      res.writeHead(200, { 'content-type': 'text/xml;charset=UTF-8' });
      res.end(Buffer.from(searchHtml(dataset, fields, cap, emitBanner, sessionEpoch), charset));
      return;
    }

    if (url.pathname.endsWith('/DetalheProcessoConsultaPublica/listView.seam')) {
      counts['detail'] = (counts['detail'] ?? 0) + 1;
      const ca = url.searchParams.get('ca') ?? '';
      const found = resolveCa(dataset, ca, sessionEpoch);
      if (found === null) {
        res.writeHead(302, { location: `${APP}/ConsultaPublica/listView.seam` });
        res.end();
        return;
      }
      res.writeHead(200, { 'content-type': 'text/html;charset=ISO-8859-1' });
      res.end(Buffer.from(detailHtml(found), charset));
      return;
    }

    if (url.pathname.endsWith('/reportPDF.seam')) {
      counts['pdf'] = (counts['pdf'] ?? 0) + 1;
      if (fault?.htmlInsteadOfPdf === true) {
        res.writeHead(200, { 'content-type': 'text/html' });
        res.end('<html><body>sessão expirada</body></html>'.padEnd(4000, ' '));
        return;
      }
      // The real endpoint hands the file over through the document store.
      res.writeHead(302, {
        location: `${APP}/seam/docstore/document.seam?docId=1&cid=${String(Date.now() % 100000)}`,
      });
      res.end();
      return;
    }

    if (url.pathname.endsWith('/reportReciboPDF.seam') || url.pathname.includes('/docstore/')) {
      counts['docstore'] = (counts['docstore'] ?? 0) + 1;
      if (fault?.htmlInsteadOfPdf === true) {
        res.writeHead(200, { 'content-type': 'text/html' });
        res.end('<html><body>sessão expirada</body></html>'.padEnd(4000, ' '));
        return;
      }
      let pdf = syntheticPdf(url.searchParams.get('idProcessoDoc') ?? 'cover');
      if (fault?.truncatePdfAt !== undefined) pdf = pdf.subarray(0, fault.truncatePdfAt);
      res.writeHead(200, {
        'content-type': 'application/pdf',
        'content-length': String(pdf.byteLength),
      });
      res.end(pdf);
      return;
    }

    res.writeHead(404, { 'content-type': 'text/plain' });
    res.end('not found');
  }

  const host = options.host ?? '127.0.0.1';
  await new Promise<void>((resolve) => server.listen(options.port ?? 0, host, resolve));
  const address = server.address() as AddressInfo;

  return {
    url: `http://${host === '0.0.0.0' ? '127.0.0.1' : host}:${String(address.port)}`,
    port: address.port,
    dataset,
    counts,
    inject: (fault) => {
      pending = fault;
      pendingLeft = fault.times ?? 1;
    },
    clearFaults: () => {
      pending = null;
      pendingLeft = 0;
    },
    searchActionId: () => actionId,
    close: () =>
      new Promise<void>((resolve, reject) =>
        server.close((err) => (err === undefined || err === null ? resolve() : reject(err))),
      ),
  };
}

// ───────────────────────────── rendering ─────────────────────────────

function listViewHtml(actionId: string, captcha: boolean): string {
  const dateFields = ['Inicio', 'Fim']
    .map(
      (which) =>
        `<input name="fPP:dataAutuacaoDecoration:dataAutuacao${which}InputDate" value=""/>` +
        `<input name="fPP:dataAutuacaoDecoration:dataAutuacao${which}InputCurrentDate" value=""/>`,
    )
    .join('');

  return `<!DOCTYPE html><html><head><title>Consulta pública</title>
<script>
function executarReCaptcha() { if (${captcha ? 'true' : 'false'}) { grecaptcha.execute(); return false; } executarPesquisa(); }
executarPesquisa=function(){A4J.AJAX.Submit('fPP',null,{'similarityGroupingId':'${actionId}','actionUrl':'${APP}/ConsultaPublica/listView.seam','parameters':{'${actionId}':'${actionId}'} })};
</script></head><body>
<form id="fPP" name="fPP" method="post" action="${APP}/ConsultaPublica/listView.seam">
  <input name="fPP:numProcesso-inputNumeroProcessoDecoration:numProcesso-inputNumeroProcesso" value=""/>
  <input name="fPP:j_id162:processoReferenciaInput" value=""/>
  <input name="fPP:dnp:nomeParte" value=""/>
  <input name="fPP:j_id180:nomeAdv" value=""/>
  <input name="fPP:j_id189:classeJudicial" value=""/>
  <input name="fPP:dpDec:documentoParte" value=""/>
  <input name="fPP:Decoration:numeroOAB" value=""/>
  <select name="fPP:Decoration:estadoComboOAB"><option value=""></option></select>
  <input name="fPP:Decoration:j_id223" value=""/>
  ${dateFields}
  <input type="submit" id="fPP:searchProcessos" name="fPP:searchProcessos" value="Pesquisar"/>
  <input type="hidden" name="javax.faces.ViewState" value="j_id1"/>
</form></body></html>`;
}

function buttonTrapHtml(): string {
  // ~2.8 KB in the real site, and crucially it re-renders the message panel, not the grid.
  return `<?xml version="1.0"?><html><head>
<meta name="Ajax-Response" content="true"/><meta name="Ajax-Update-Ids" content="fPP:j_id248"/>
</head><body><span id="fPP:j_id248"></span></body></html>`;
}

function searchHtml(
  dataset: Dataset,
  fields: Record<string, string>,
  cap: number,
  emitBanner: boolean,
  epoch: number,
): string {
  const ini = brToIso(fields['fPP:dataAutuacaoDecoration:dataAutuacaoInicioInputDate'] ?? '');
  const fim = brToIso(fields['fPP:dataAutuacaoDecoration:dataAutuacaoFimInputDate'] ?? '');
  const classeFilter = (fields['fPP:j_id189:classeJudicial'] ?? '').trim();

  let matches: SyntheticCase[] = [];
  for (const [day, cases] of dataset.byDay) {
    if (ini !== '' && day < ini) continue;
    if (fim !== '' && day > fim) continue;
    matches.push(...cases);
  }
  if (classeFilter !== '') {
    // Measured on the real site: the filter is accent-insensitive and matches by **prefix**.
    const needle = fold(classeFilter);
    matches = matches.filter((c) => fold(c.classe).startsWith(needle));
  }
  matches.sort((a, b) => a.numero.localeCompare(b.numero));

  const truncated = matches.length > cap;
  const shown = matches.slice(0, cap);

  const rows = shown
    .map(
      (c) => `<tr class="rich-table-row">
  <td class="rich-table-cell" id="fPP:processosTable:${c.idOrigem}:j_id255">
    <a onclick="openPopUp('Consulta pública','${APP}/ConsultaPublica/DetalheProcessoConsultaPublica/listView.seam?ca=${caFor(c, epoch)}')"></a>
  </td>
  <td class="rich-table-cell" id="fPP:processosTable:${c.idOrigem}:j_id257">${escapeHtml(c.classe)}
    <a onclick="openPopUp('x','${APP}/ConsultaPublica/DetalheProcessoConsultaPublica/listView.seam?ca=${caFor(c, epoch)}')"><b class="btn-block">${c.sigla} ${c.numero} - Assunto</b></a>
    ${escapeHtml(c.parteAtiva)} X ${escapeHtml(c.partePassiva)}
  </td>
  <td class="rich-table-cell" id="fPP:processosTable:${c.idOrigem}:j_id263">${escapeHtml(c.ultimaMovimentacao.descricao)} (${toBrDateTime(c.ultimaMovimentacao.dataHora)})</td>
</tr>`,
    )
    .join('\n');

  const banner =
    truncated && emitBanner
      ? `<div class="alert alert-danger">Sua consulta retornou muitos processos e somente os ${String(cap)} primeiros serão exibidos. Por favor, refine sua pesquisa.</div>`
      : '';

  // With no results the footer renders without a number — the real "empty" marker.
  const count = shown.length === 0 ? '' : String(shown.length);

  return `<?xml version="1.0" encoding="UTF-8"?><html><head>
<meta name="Ajax-Response" content="true"/><meta name="Ajax-Update-Ids" content="fPP:processosGridPanel"/>
</head><body><div id="fPP:processosGridPanel">${banner}
<table id="fPP:processosTable"><tbody>${rows}</tbody>
<tfoot><tr><td><div><div><span class="text-muted">${count} resultados encontrados</span></div></div></td></tr></tfoot>
</table></div></body></html>`;
}

function detailHtml(c: SyntheticCase): string {
  const property = (label: string, value: string): string =>
    `<div class="propertyView "><div class="name"><label>${escapeHtml(label)}</label></div>` +
    `<div class="value col-sm-12 ">${escapeHtml(value)}</div></div>`;

  const documents = c.documentos
    .map(
      (d) => `<tr><td>
      <a onclick="openPopUp('comprovante','${APP}/Processo/reportReciboPDF.seam?idBin=${d.idBin}&amp;idProcessoDoc=${d.idDoc}&amp;idProcessoTrf=${c.idOrigem}')">Visualizar documentos</a>
      ${toBrDateTime(d.juntadoEm)} - ${escapeHtml(d.tipo)} (${escapeHtml(d.tipo)})
    </td></tr>`,
    )
    .join('\n');

  return `<!DOCTYPE html><html><head><title>Detalhe</title></head><body>
${property('Número Processo', c.numero)}
${property('Data da Distribuição', toBrDate(c.dataAutuacao))}
${property('Classe Judicial', `${c.classe} (198)`)}
${property('Assunto', c.assunto)}
${property('Jurisdição', 'TRF5')}
<div class="propertyView "><div class="name"><label> </label></div><div class="value col-sm-12 ">
  <b>Órgão Julgador</b><br/>Gab TESTE</div></div>
${property('Processo referência', c.numero)}
<div class="rich-panel-header">Polo ativo</div>
<div class="rich-panel-body"><table><tr>
  <td><span class="text-bold">${escapeHtml(c.parteAtiva)} - CNPJ: 08.409.021/0001-77 (APELANTE)</span></td><td>Ativo</td>
</tr></table></div>
<div class="rich-panel-header">Polo Passivo</div>
<div class="rich-panel-body"><table><tr>
  <td><span class="text-bold">${escapeHtml(c.partePassiva)} - CNPJ: 00.394.460/0216-53 (APELADO)</span></td><td>Ativo</td>
</tr></table></div>
<div><span>${toBrDateTime(c.ultimaMovimentacao.dataHora)} - ${escapeHtml(c.ultimaMovimentacao.descricao)}</span></div>
<table id="j_id146:processoDocumentoGridTab">${documents}</table>
</body></html>`;
}

/** A minimal but structurally valid PDF, large enough to clear the size floor. */
export function syntheticPdf(seed: string): Buffer {
  const filler = `% ${seed} `.repeat(400);
  return Buffer.from(
    `%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n${filler}\ntrailer<</Root 1 0 R>>\n%%EOF\n`,
    'latin1',
  );
}

// ───────────────────────────── helpers ─────────────────────────────

function caFor(c: SyntheticCase, epoch: number): string {
  // The token is session-bound: bumping the epoch invalidates every one already issued.
  return `${epoch.toString(16).padStart(4, '0')}${Number(c.idOrigem).toString(16)}`;
}

function resolveCa(dataset: Dataset, ca: string, epoch: number): SyntheticCase | null {
  if (ca.length < 5) return null;
  if (parseInt(ca.slice(0, 4), 16) !== epoch) return null;
  const id = String(parseInt(ca.slice(4), 16));
  return dataset.byId.get(id) ?? null;
}

async function readBody(req: IncomingMessage): Promise<string> {
  if (req.method !== 'POST') return '';
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(chunk as Buffer);
  // The body arrives latin1-encoded, as the real form does.
  return Buffer.concat(chunks).toString('latin1');
}

function parseForm(body: string): Record<string, string> {
  const fields: Record<string, string> = {};
  for (const pair of body.split('&')) {
    if (pair === '') continue;
    const [rawKey = '', rawValue = ''] = pair.split('=');
    fields[decodeLatin1Component(rawKey)] = decodeLatin1Component(rawValue);
  }
  return fields;
}

/** Percent-decoding that treats each byte as latin1, matching how the form was encoded. */
function decodeLatin1Component(value: string): string {
  return value
    .replace(/\+/g, ' ')
    .replace(/%([0-9a-fA-F]{2})/g, (_, hex: string) => String.fromCharCode(parseInt(hex, 16)));
}

function fold(text: string): string {
  return text.normalize('NFD').replace(/[̀-ͯ]/g, '').toUpperCase().trim();
}

function brToIso(value: string): string {
  const match = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec(value.trim());
  return match === null ? '' : `${match[3] ?? ''}-${match[2] ?? ''}-${match[1] ?? ''}`;
}

function toBrDate(iso: string): string {
  const [y = '', m = '', d = ''] = iso.split('-');
  return `${d}/${m}/${y}`;
}

function toBrDateTime(value: string): string {
  const [date = '', time = '00:00:00'] = value.split(' ');
  return `${toBrDate(date)} ${time}`;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
